### ISSUE TITLE
Single vs Multiple csproj in directory behavior

### ISSUE THREAD

**Issue by haritha-mohan** [dotnet/xcsync#58] opened 2024-09-06 19:06 UTC
If there is only one .csproj in a directory, the `-p, --project` option should accept the directory path and id the csproj present.

For reference, this is the current behavior:
`dotnet xcsync generate -p ~/test/test-project`

> '/Users/mcumming/test/test-project' is not a valid path to a .NET project or a directory.

However, the csproj path will have to be explicitly specified if there are multiple csproj files present in the directory.

**Comment by haritha-mohan** [comment] 2024-10-04 01:53
https://github.com/dotnet/xcsync/blob/a0278419644d6fca37aed94efe26a8ba45d4dfd5/src/xcsync/Commands/BaseCommand.cs#L118

🤔

**Comment by mcumming** [comment] 2024-11-19 03:29
Duplicate of #57

**Closed** 2024-11-19 03:28 UTC
Labels: area-commandlinehandling
